name: Compile

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: true
      - uses: actions/setup-node@v4
        with:
          node-version: "24"
      - run: go version
      - run: make test
      - run: yarn --cwd ./browser-test && make browser-test
      - run: make build
      - run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'bot'
          rm .gitignore
          if git diff --stat | grep dist/ --quiet; then
            echo "There were changes. Committing.";
            git add --force dist/;
            git commit -m "[GitHub action] Wasm module";
            git push
          else
            echo "No changes to commit. Skipping.";
          fi
